#!/usr/local/cpanel/3rdparty/bin/perl

#
#                                      Copyright 2026 WebPros International, LLC
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited.

package ea_ioncube15::find_latest_version;

use strict;
use warnings;

use lib "../ea-tools/lib/ea4_tool";    # assumes ea-tools is checked out next to this repo
use ea4_tool::util ();

use HTML::TreeBuilder;

ea4_tool::util::find_latest_version( \&_get_required, \&_add_sum ) if !caller();

###############
#### helpers ##
###############

sub _get_required {
    my ($http, $look_for) = @_;

    $look_for //= "15\.0";

    my $listing_url = "https://ioncube.com/loaders.php";
    my $res         = $http->get($listing_url);
    if ( !$res->{success} ) {
        die "Could not GET ioncube dist page ($res->{status} $res->{reason})\n";
    }

    # php85 is only supported on their beta version 15.5, not on 15.0

    my @versions = _scrape_page( 'Linux (64 bits)', $res->{content} );
    my ($version, $url);

    foreach my $version_node (@versions) {
        my $loop_version = $version_node->{version};
        my $loop_url     = $version_node->{url};

        # Ensure we only get version 15.x.x for ea-ioncube15
        if ( $loop_version =~ m/^\Q$look_for\E/ ) {
            $version = $loop_version;
            $url     = $loop_url;
        }
    }

    die "Did not find a verion candidate for this package.\n" if !$version;

    my $ridx = rindex( $url, '/' );
    die "Unable to determine the tarball name from \"$url\"\n" if ( $ridx < 0 );
    my $name = substr( $url, $ridx + 1 );

    return ( $version, $url, $name );
}

sub _add_sum {
    my ( $http, $hr ) = @_;

    # Optional: Set $hr->{tarball}{sum}{hex} and $hr->{tarball}{sum}{type} (sha256, sha1, md5, anything Digest.pm can handle)
    #           die if there is a problem determining either of those values
    # otherwise this is a no-op

    return;
}

##########################
#### helper helpers lol ##
##########################

# The landing page for ioncube is structured like so.   I am anchoring on the
# Linux (64 bits) string, from there I can go up and around for the href and
# the version number 10.3.9.
#
#       tr
#        td
#         Linux (64 bits)
#         a HREF https://ioncube24.com
#          img
#        td
#         a HREF https://downloads.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64.tar.gz
#          tar.gz
#        td
#         a HREF https://downloads.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64.zip
#          zip
#        td
#          10.3.9
#        td
#          2019-10-11

my @anchors;

use constant max_depth => 30;

sub _recursive_descent {
    my ( $type, $node, $depth, $parent ) = @_;

    die "Recursion limit reached, have they changed the landing page?\n" if ( $depth > max_depth );

    # If $node is a reference, then it is an HTML::Element.

    if ( ref $node ) {

        # there is a tag associated with $node, for example "html" or
        # "li".

        my @children = $node->content_list();
        for my $child_node (@children) {
            _recursive_descent( $type, $child_node, $depth + 1, $node );
        }
    }
    else {

        # If $node is not a reference, then it is just a piece of text
        # from the HTML file.

        if ( $node =~ m/\Q$type\E/ ) {
            push (@anchors, $parent);
        }
    }

    return;
}

sub _scrape_page {
    my ( $type, $html ) = @_;

    my $treebuilder = HTML::TreeBuilder->new_from_content($html);
    my $root        = $treebuilder->elementify();

    @anchors = ();
    _recursive_descent( $type, $root, 0, undef );

    if ( !@anchors ) {
        die "Unable to identify the x86-64 version of ioncube, perhaps they have changed their landing page?\n";
    }

    # the anchor is the td, where we find the string Linux (64 bits) in, we then
    # need to hop over to 2 parallel tds, walk it back up to the tr and over to the tds.

    my @versions;

    foreach my $anchor (@anchors) {
        my $tr = $anchor->parent();

        my $scraped_version;
        my $scraped_tarball;

        my @children = $tr->content_list();
        for my $child_node (@children) {
            if ( ref($child_node) && $child_node->tag() eq 'td' ) {
                my @sub_children = $child_node->content_list();
                if (@sub_children) {
                    my $text_node = $sub_children[0];
                    if ( !ref($text_node) && $text_node =~ m/(\d+\.\d+\.\d+)/ ) {
                        $scraped_version = $1;
                    }
                    if ( !$scraped_tarball && ref($text_node) && $text_node->tag() eq 'a' ) {
                        my $href = $text_node->attr('href');
                        if ( $href =~ m/\.tar\.gz$/ ) {
                            $scraped_tarball = $href;
                        }
                    }
                    foreach my $node (@sub_children) {
                        my $version;
                        my $tarball;

                        if ( !ref($node) && $node =~ m/(\d+\.\d+\.\d+)/ ) {
                            $version = $1;
                        }
                        if ( !$tarball && ref($node) && $node->tag() eq 'a' ) {
                            my $href = $node->attr('href');
                            if ( $href =~ m/\.tar\.gz$/ ) {
                                $tarball = $href;
                            }
                        }

                        if ($version) {
                            $tarball //= "Unknown";
                        }
                    }
                }
            }
        }

        push (@versions, { version => "$scraped_version", url => "$scraped_tarball" }) if ($scraped_version);
    }

    if ( !@versions ) {
        die "Could not find version and/or the tarball, perhaps they changed the format of the landing page?\n";
    }

    return @versions;
}

1;

__END__

=encoding utf-8

=head1 README

The tarball does not contain the version in its name.

There is a different distribution archive per architecture:

OBS builds the 32-bit targets as arch 'i586', and more typical
32-bit architecture is 'i386', but 32-bit archive is named 'x86'.
64-bit archive is 'x86-64', rather than 'x86_64'.

We only do 64 bit.

